# Generated by Django 3.1 on 2020-08-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=20)),
                ('synopsis', models.CharField(max_length=500)),
                ('poster_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
